# all these path ar set relative to the input directory (i.e., vcf_dir specified in tsinfer_Eddie.yaml)
raw_vcf: "RawVCF/Combined_ReducedSamples1.vcf.gz"
aligned_focal: "testAligned.txt"
no_estsfs_chunks: 3
estsfs_config: "config-kimura_3o.txt"
estsfs_seed: "seedfile.txt"
