raw_vcf: "/home/v1jobste/HLab/share/Snakemake/Data/RawVCF/Combined_ReducedSamples1.vcf.gz"
aligned_focal: "/home/v1jobste/HLab/share/Snakemake/Data/testAligned.txt"
no_estsfs_chunks: 3
estsfs_config: "/home/v1jobste/HLab/share/Snakemake/Data/config-kimura_3o.txt"
estsfs_seed: "/home/v1jobste/HLab/share/Snakemake/Data/seedfile.txt"
